### ISSUE TITLE
Include a coding standard

### ISSUE THREAD

**Issue by azdanov** [sebbaum/generator-laravel-5#6]
What I am thinking is to either to include [`PHP_CodeSniffer`](https://github.com/squizlabs/PHP_CodeSniffer) and/or [`PHP-CS-Fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer) with a default set of rules.

For `PHP-CS-Fixer` I use this [config](https://gist.github.com/azdanov/8f637142115feebf4b44e11a0971e5cb). And for `PHP_CodeSniffer` I use [doctrine/coding-standard](https://github.com/doctrine/coding-standard).

It would be cool to create something similar for a Laravel project which works out of the box.

**Comment by sebbaum** [comment]
Hi @azdanov,
thanks for your idea. I also think that code quality is important. I worked with PHP_CodeSniffer in the past.
I'll evaluate your idea a little further.

Also feel free to send a PR.

Cheers
Sebastian

**Comment by sebbaum** [comment]
> I am wondering which coding-standard rulesets would fit.
Well, that's a good question. You're right, antonioribeiro/laravelcs is too old.
The other one looks promising. I also like the fact that it can be run with an artisan command. Maybe I can give it a try on Monday on one of my projects.

**Comment by azdanov** [comment]
Another interesting alternative is [symplify/easyCodingStandard](https://github.com/symplify/easyCodingStandard/).

**Comment by sebbaum** [comment]
Nice, thanks. I'll take it into consideration.

**Comment by sebbaum** [comment]
Hi @azdanov,
I found some time to check your suggestion of ECS. I like it and I'll integrate it in the next release 1.5.0.

Concerning the default checks, I'll choose a less strict check. Developers can then select their preferred config.

Thanks again for pointing me at this tool.

Cheers
Sebastian
